name: Build ASP.NET Framework Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet Packages
        run: |
          nuget restore FiserveDotnetFrameworkTest.slnx -PackagesDirectory packages

      - name: Build Solution
        run: |
          msbuild FiserveDotnetFrameworkTest.slnx /p:Configuration=Release

      - name: Publish ASP.NET Application
        run: |
          msbuild FiserveDotnetFrameworkTest.csproj `
            /p:Configuration=Release `
            /p:DeployOnBuild=true `
            /p:DeployDefaultTarget=WebPublish `
            /p:WebPublishMethod=FileSystem `
            /p:DeleteExistingFiles=true `
            /p:PublishUrl="${{ github.workspace }}\publish"

      - name: Verify Publish Output
        run: |
          Write-Host "===== PUBLISH DIRECTORY ====="
          Get-ChildItem "${{ github.workspace }}\publish" -Recurse

      - name: Install WiX Toolset
        shell: pwsh
        run: |
          dotnet tool install --global wix
           
      - name: Build MSI
        shell: pwsh
        run: |
          Write-Host "===== BUILDING MSI ====="

          wix build `
            -acceptEula wix7 `
            -d PublishDir="${{ github.workspace }}\publish" `
            Installer\Product.wxs `
            -o "${{ github.workspace }}\FiserveDotnetFrameworkTest.msi"


          
      - name: Verify MSI
        shell: pwsh
        run: |
          Write-Host "===== MSI OUTPUT ====="
          Get-Item "${{ github.workspace }}\FiserveDotnetFrameworkTest.msi"
      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FiserveDotnetFrameworkTest-MSI
          path: ${{ github.workspace }}\FiserveDotnetFrameworkTest.msi


